apiVersion: v1
kind: Service
metadata:
  name: transaction-analyzer-service
spec:
  type: LoadBalancer
  selector:
    app: transaction-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000